"""v0.1 baseline

Revision ID: 10691de66f04
Revises: 
Create Date: 2026-02-11 00:16:44.271396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10691de66f04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='api_token_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_api_token_token_hash'), 'api_token', ['token_hash'], unique=True)
    op.create_table('ipam_pool',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('gateway', sa.String(length=64), nullable=False),
    sa.Column('quarantine_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cidr')
    )
    op.create_table('node_endpoint',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('VPS_T', 'VPS_E', name='node_role'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('public_ipv4', sa.String(length=64), nullable=False),
    sa.Column('fqdn', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_node_endpoint_role'), 'node_endpoint', ['role'], unique=False)
    op.create_table('tg_user',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('devices_max', sa.Integer(), nullable=False),
    sa.Column('entitlement_status', sa.Enum('ACTIVE', 'GRACE', 'BLOCKED', name='entitlement_status'), nullable=False),
    sa.Column('grace_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('device',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='device_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_user_id'), 'device', ['user_id'], unique=False)
    op.create_table('ipam_lease',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('owner_type', sa.Enum('USER', 'DEVICE', 'PEER', name='owner_type'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'QUARANTINED', 'RELEASED', name='ipam_lease_status'), nullable=False),
    sa.Column('quarantined_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['ipam_pool.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'ip', name='uq_ipam_pool_ip')
    )
    op.create_index(op.f('ix_ipam_lease_pool_id'), 'ipam_lease', ['pool_id'], unique=False)
    op.create_table('outbox_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('APPLY_BUNDLE', 'UPSERT_USER', 'REVOKE_USER', 'REVOKE_CONNECTION', 'WG_PEER_UPSERT', 'WG_PEER_REMOVE', name='outbox_event_type'), nullable=False),
    sa.Column('role_target', sa.Enum('VPS_T', 'VPS_E', name='outbox_role_target'), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INFLIGHT', 'SENT', 'FAILED', name='outbox_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node_endpoint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbox_event_available_at'), 'outbox_event', ['available_at'], unique=False)
    op.create_index(op.f('ix_outbox_event_status'), 'outbox_event', ['status'], unique=False)
    op.create_table('connection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('protocol', sa.Enum('VLESS_REALITY', 'HYSTERIA2', 'WIREGUARD', name='connection_protocol'), nullable=False),
    sa.Column('mode', sa.Enum('DIRECT', 'CHAIN', name='connection_mode'), nullable=False),
    sa.Column('variant', sa.Enum('B1', 'B2', 'B3', 'B5', name='connection_variant'), nullable=False),
    sa.Column('profile_name', sa.String(length=64), nullable=False),
    sa.Column('custom_overrides_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='connection_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_device_id'), 'connection', ['device_id'], unique=False)
    op.create_index(op.f('ix_connection_user_id'), 'connection', ['user_id'], unique=False)
    op.create_table('outbox_delivery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outbox_event_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='delivery_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node_endpoint.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outbox_event_id'], ['outbox_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outbox_event_id', 'node_id', name='uq_outbox_delivery_event_node')
    )
    op.create_index(op.f('ix_outbox_delivery_next_attempt_at'), 'outbox_delivery', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_delivery_node_id'), 'outbox_delivery', ['node_id'], unique=False)
    op.create_index(op.f('ix_outbox_delivery_outbox_event_id'), 'outbox_delivery', ['outbox_event_id'], unique=False)
    op.create_index(op.f('ix_outbox_delivery_status'), 'outbox_delivery', ['status'], unique=False)
    op.create_table('wireguard_peer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('peer_public_key', sa.String(length=256), nullable=False),
    sa.Column('lease_id', sa.UUID(), nullable=False),
    sa.Column('preshared_key', sa.String(length=256), nullable=True),
    sa.Column('allowed_ips', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='wireguard_peer_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lease_id'], ['ipam_lease.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lease_id'),
    sa.UniqueConstraint('peer_public_key')
    )
    op.create_index(op.f('ix_wireguard_peer_device_id'), 'wireguard_peer', ['device_id'], unique=False)
    op.create_index(op.f('ix_wireguard_peer_user_id'), 'wireguard_peer', ['user_id'], unique=False)
    op.create_table('connection_revision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='connection_revision_status'), nullable=False),
    sa.Column('camouflage_sni_id', sa.Integer(), nullable=True),
    sa.Column('effective_config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connection_revision_active_slot', 'connection_revision', ['connection_id', 'status', 'slot'], unique=False)
    op.create_index(op.f('ix_connection_revision_connection_id'), 'connection_revision', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_revision_connection_id'), table_name='connection_revision')
    op.drop_index('ix_connection_revision_active_slot', table_name='connection_revision')
    op.drop_table('connection_revision')
    op.drop_index(op.f('ix_wireguard_peer_user_id'), table_name='wireguard_peer')
    op.drop_index(op.f('ix_wireguard_peer_device_id'), table_name='wireguard_peer')
    op.drop_table('wireguard_peer')
    op.drop_index(op.f('ix_outbox_delivery_status'), table_name='outbox_delivery')
    op.drop_index(op.f('ix_outbox_delivery_outbox_event_id'), table_name='outbox_delivery')
    op.drop_index(op.f('ix_outbox_delivery_node_id'), table_name='outbox_delivery')
    op.drop_index(op.f('ix_outbox_delivery_next_attempt_at'), table_name='outbox_delivery')
    op.drop_table('outbox_delivery')
    op.drop_index(op.f('ix_connection_user_id'), table_name='connection')
    op.drop_index(op.f('ix_connection_device_id'), table_name='connection')
    op.drop_table('connection')
    op.drop_index(op.f('ix_outbox_event_status'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_available_at'), table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_index(op.f('ix_ipam_lease_pool_id'), table_name='ipam_lease')
    op.drop_table('ipam_lease')
    op.drop_index(op.f('ix_device_user_id'), table_name='device')
    op.drop_table('device')
    op.drop_table('tg_user')
    op.drop_index(op.f('ix_node_endpoint_role'), table_name='node_endpoint')
    op.drop_table('node_endpoint')
    op.drop_table('ipam_pool')
    op.drop_index(op.f('ix_api_token_token_hash'), table_name='api_token')
    op.drop_table('api_token')
    # ### end Alembic commands ###
