"""v0.2 core changes

Revision ID: 92b17df9933b
Revises: 10691de66f04
Create Date: 2026-02-11 00:46:52.872886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b17df9933b'
down_revision: Union[str, Sequence[str], None] = '10691de66f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new delivery status without breaking existing DBs.
    op.execute(
        "DO $$ BEGIN "
        "ALTER TYPE delivery_status ADD VALUE IF NOT EXISTS 'DEAD'; "
        "EXCEPTION WHEN undefined_object THEN NULL; "
        "END $$;"
    )

    # Ensure the enum exists before adding a column that references it.
    user_role_enum = sa.Enum("USER", "ADMIN", "SUPERADMIN", name="user_role")
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('grafana_otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['tg_user.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grafana_otp_code_hash'), 'grafana_otp', ['code_hash'], unique=True)
    op.create_index(op.f('ix_grafana_otp_expires_at'), 'grafana_otp', ['expires_at'], unique=False)
    op.create_index(op.f('ix_grafana_otp_telegram_id'), 'grafana_otp', ['telegram_id'], unique=False)
    op.add_column('outbox_delivery', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox_delivery', sa.Column('locked_by', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_outbox_delivery_locked_until'), 'outbox_delivery', ['locked_until'], unique=False)
    op.add_column('tg_user', sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPERADMIN', name='user_role'), nullable=False, server_default='USER'))
    op.create_index(op.f('ix_tg_user_role'), 'tg_user', ['role'], unique=False)
    op.add_column('wireguard_peer', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))

    # v0.1 bug could create multiple WireGuard peers per device during revision rotation.
    # v0.2 expects a single peer per device (DB + agent artifacts are keyed by device_id),
    # so we deduplicate before enforcing uniqueness.
    op.execute(
        """
        WITH desired AS (
          SELECT DISTINCT ON (c.device_id)
            c.device_id,
            (r.effective_config_json->>'device_public_key') AS desired_pub,
            r.created_at AS rev_created_at
          FROM connection c
          JOIN connection_revision r ON r.connection_id = c.id
          WHERE c.protocol = 'WIREGUARD' AND c.status = 'ACTIVE'
            AND r.status = 'ACTIVE' AND r.slot = 0
          ORDER BY c.device_id, r.created_at DESC
        ),
        ranked AS (
          SELECT
            wp.id,
            wp.device_id,
            wp.lease_id,
            row_number() OVER (
              PARTITION BY wp.device_id
              ORDER BY
                COALESCE(wp.peer_public_key = d.desired_pub, false) DESC,
                (wp.status = 'ACTIVE') DESC,
                wp.created_at DESC,
                wp.id DESC
            ) AS rn
          FROM wireguard_peer wp
          LEFT JOIN desired d ON d.device_id = wp.device_id
        ),
        to_keep AS (
          SELECT device_id, lease_id
          FROM ranked
          WHERE rn = 1
        ),
        to_delete AS (
          SELECT id, lease_id
          FROM ranked
          WHERE rn > 1
        ),
        release_leases AS (
          UPDATE ipam_lease l
          SET status = 'RELEASED',
              quarantined_until = NULL
          WHERE l.id IN (SELECT lease_id FROM to_delete)
          RETURNING 1
        ),
        assign_leases AS (
          -- v0.2 allocates WireGuard leases by DEVICE (device_id), not PEER.
          UPDATE ipam_lease l
          SET owner_type = 'DEVICE',
              owner_id = k.device_id,
              status = 'ACTIVE',
              quarantined_until = NULL
          FROM to_keep k
          WHERE l.id = k.lease_id
          RETURNING 1
        ),
        activate_peers AS (
          UPDATE wireguard_peer wp
          SET status = 'ACTIVE'
          FROM desired d
          WHERE wp.device_id = d.device_id
          RETURNING 1
        ),
        deleted_peers AS (
          DELETE FROM wireguard_peer
          WHERE id IN (SELECT id FROM to_delete)
          RETURNING 1
        )
        SELECT 1;
        """
    )

    op.drop_index(op.f('ix_wireguard_peer_device_id'), table_name='wireguard_peer')
    op.create_index(op.f('ix_wireguard_peer_device_id'), 'wireguard_peer', ['device_id'], unique=True)
    # ### end Alembic commands ### 


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wireguard_peer_device_id'), table_name='wireguard_peer')
    op.create_index(op.f('ix_wireguard_peer_device_id'), 'wireguard_peer', ['device_id'], unique=False)
    op.drop_column('wireguard_peer', 'updated_at')
    op.drop_index(op.f('ix_tg_user_role'), table_name='tg_user')
    op.drop_column('tg_user', 'role')
    op.drop_index(op.f('ix_outbox_delivery_locked_until'), table_name='outbox_delivery')
    op.drop_column('outbox_delivery', 'locked_by')
    op.drop_column('outbox_delivery', 'locked_until')
    op.drop_index(op.f('ix_grafana_otp_telegram_id'), table_name='grafana_otp')
    op.drop_index(op.f('ix_grafana_otp_expires_at'), table_name='grafana_otp')
    op.drop_index(op.f('ix_grafana_otp_code_hash'), table_name='grafana_otp')
    op.drop_table('grafana_otp')
    # ### end Alembic commands ###
