#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections.abc import Mapping
import ipaddress
from pathlib import Path
from typing import Any

import yaml


def _read_yaml(path: Path) -> dict[str, Any]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        raise SystemExit(f"values file must be a YAML mapping: {path}")
    return raw


def _merge(base: dict[str, Any], override: Mapping[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, Mapping) and isinstance(merged.get(key), dict):
            merged[key] = _merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def _mapping(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _endpoint_role(roles: Mapping[str, Any]) -> dict[str, Any]:
    transit_role = _mapping(roles.get("transit"))
    endpoint_override = _mapping(roles.get("endpoint"))
    if endpoint_override:
        return _merge(transit_role, endpoint_override)
    return transit_role


def _ipv4(value: Any, field: str) -> str:
    address = str(value or "").strip()
    try:
        if ipaddress.ip_address(address).version != 4:
            raise ValueError
    except ValueError as exc:
        raise SystemExit(f"{field} must be an IPv4 address") from exc
    return address


def _port(value: Any, field: str) -> int:
    try:
        port = int(value)
    except (TypeError, ValueError) as exc:
        raise SystemExit(f"{field} must be a valid port") from exc
    if not 1 <= port <= 65535:
        raise SystemExit(f"{field} must be a valid port")
    return port


def render(values: dict[str, Any]) -> str:
    architecture = _mapping(values.get("architecture"))
    endpoint_ingress = _mapping(architecture.get("endpointIngress"))
    if not endpoint_ingress.get("enabled"):
        raise SystemExit("architecture.endpointIngress.enabled=true is required")

    service_ip = _ipv4(
        _mapping(endpoint_ingress.get("serviceFacing")).get("publicIp"),
        "architecture.endpointIngress.serviceFacing.publicIp",
    )
    shard_ips = sorted(
        {
            _ipv4(shard.get("publicIp"), "architecture.endpointIngress.shards[].publicIp")
            for shard in endpoint_ingress.get("shards", [])
            if isinstance(shard, dict) and str(shard.get("state") or "active").strip().lower() == "active"
        }
    )
    if not shard_ips:
        raise SystemExit("architecture.endpointIngress requires at least one active shard")

    gateway = _mapping(values.get("gateway"))
    roles = _mapping(gateway.get("roles"))
    endpoint_role = _endpoint_role(roles)
    udp_port = _port(
        _mapping(endpoint_role.get("ports")).get("publicUdp"),
        "gateway.roles.endpoint.ports.publicUdp",
    )
    udp_ports = {udp_port}
    hysteria_salamander = _mapping(_mapping(gateway.get("hysteria")).get("salamander"))
    if hysteria_salamander.get("enabled"):
        udp_ports.add(_port(hysteria_salamander.get("port"), "gateway.hysteria.salamander.port"))

    lines = [
        "# Generated by deploy/k3s/endpoint-egress-firewall.py. Do not edit.",
        "table ip tracegate_endpoint_egress {",
        "  chain prerouting {",
        "    type nat hook prerouting priority dstnat - 10; policy accept;",
    ]
    lines.extend(
        f'    iifname "eth0" ip daddr {shard_ip} udp dport {port} dnat to {service_ip}:{port}'
        for shard_ip in shard_ips
        for port in sorted(udp_ports)
    )
    lines.extend(
        [
            "  }",
            "  chain postrouting {",
            "    type nat hook postrouting priority srcnat - 10; policy accept;",
            f'    oifname "eth0" ip saddr {{ {", ".join(shard_ips)} }} snat to {service_ip}',
            "  }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render Endpoint shard DNAT and egress identity policy.")
    parser.add_argument("--chart-values", required=True, type=Path)
    parser.add_argument("--values", required=True, type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = render(_merge(_read_yaml(args.chart_values), _read_yaml(args.values)))
    if args.output:
        args.output.write_text(output, encoding="utf-8")
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
