#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections.abc import Mapping
import ipaddress
from pathlib import Path
from typing import Any

import yaml


def _read_yaml(path: Path) -> dict[str, Any]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        raise SystemExit(f"values file must be a YAML mapping: {path}")
    return raw


def _merge(base: dict[str, Any], override: Mapping[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, Mapping) and isinstance(merged.get(key), dict):
            merged[key] = _merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def _mapping(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _endpoint_role(roles: Mapping[str, Any]) -> dict[str, Any]:
    transit_role = _mapping(roles.get("transit"))
    endpoint_override = _mapping(roles.get("endpoint"))
    if endpoint_override:
        return _merge(transit_role, endpoint_override)
    return transit_role


def _port(value: Any) -> int:
    try:
        port = int(value)
    except (TypeError, ValueError):
        return 0
    return port if 1 <= port <= 65535 else 0


def render(values: dict[str, Any]) -> str:
    architecture = _mapping(values.get("architecture"))
    endpoint_ingress = _mapping(architecture.get("endpointIngress"))
    if not endpoint_ingress.get("enabled"):
        raise SystemExit("architecture.endpointIngress.enabled=true is required")

    service_ip = str(_mapping(endpoint_ingress.get("serviceFacing")).get("publicIp") or "").strip()
    if not service_ip:
        raise SystemExit("architecture.endpointIngress.serviceFacing.publicIp is required")
    try:
        if ipaddress.ip_address(service_ip).version != 4:
            raise ValueError
    except ValueError as exc:
        raise SystemExit("architecture.endpointIngress currently requires IPv4 addresses") from exc

    gateway = _mapping(values.get("gateway"))
    roles = _mapping(gateway.get("roles"))
    endpoint_role = _endpoint_role(roles)
    ports = _mapping(endpoint_role.get("ports"))
    wireguard = _mapping(values.get("wireguard"))

    tcp_ports = {_port(ports.get("publicTcp"))}
    udp_ports = {_port(ports.get("publicUdp"))}
    if wireguard.get("enabled"):
        tcp_ports.add(_port(_mapping(wireguard.get("wstunnel")).get("websocketPort")))
    tcp_ports.discard(0)
    udp_ports.discard(0)

    disabled_ips = {
        str(shard.get("publicIp") or "").strip()
        for shard in endpoint_ingress.get("shards", [])
        if isinstance(shard, dict) and str(shard.get("state") or "active").strip().lower() == "disabled"
    }
    for value in disabled_ips:
        try:
            if ipaddress.ip_address(value).version != 4:
                raise ValueError
        except ValueError as exc:
            raise SystemExit("architecture.endpointIngress currently requires IPv4 addresses") from exc

    reject_ips = sorted({service_ip, *disabled_ips})
    lines = [
        "# Generated by deploy/k3s/endpoint-ingress-firewall.py. Do not edit.",
        "table inet tracegate_endpoint_ingress {",
        "  chain input {",
        "    type filter hook input priority -10; policy accept;",
    ]
    if tcp_ports:
        lines.append(
            f"    iifname != \"lo\" ip daddr {{ {', '.join(reject_ips)} }} tcp dport {{ {', '.join(map(str, sorted(tcp_ports)))} }} reject with tcp reset"
        )
    if udp_ports:
        lines.append(
            f"    iifname != \"lo\" ct status dnat ip daddr {service_ip} udp dport {{ {', '.join(map(str, sorted(udp_ports)))} }} accept"
        )
        lines.append(
            f"    iifname != \"lo\" ip daddr {{ {', '.join(reject_ips)} }} udp dport {{ {', '.join(map(str, sorted(udp_ports)))} }} drop"
        )
    lines.extend(["  }", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the mandatory four-IP Endpoint ingress nftables policy.")
    parser.add_argument("--chart-values", required=True, type=Path)
    parser.add_argument("--values", required=True, type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = render(_merge(_read_yaml(args.chart_values), _read_yaml(args.values)))
    if args.output:
        args.output.write_text(output, encoding="utf-8")
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
