#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections.abc import Mapping
import ipaddress
from pathlib import Path
from typing import Any

import yaml


def _read_yaml(path: Path) -> dict[str, Any]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        raise SystemExit(f"values file must be a YAML mapping: {path}")
    return raw


def _merge(base: dict[str, Any], override: Mapping[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, Mapping) and isinstance(merged.get(key), dict):
            merged[key] = _merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def _mapping(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _public_ipv4(value: object, *, field_name: str) -> str:
    raw = str(value or "").strip()
    try:
        parsed = ipaddress.ip_address(raw)
    except ValueError as exc:
        raise SystemExit(f"{field_name} must be a public IPv4 address") from exc
    if parsed.version != 4 or not parsed.is_global:
        raise SystemExit(f"{field_name} must be a public IPv4 address")
    return str(parsed)


def render(values: dict[str, Any]) -> str:
    universal = _mapping(_mapping(values.get("architecture")).get("universalEntry"))
    if not universal.get("enabled"):
        raise SystemExit("architecture.universalEntry.enabled=true is required")

    endpoint_backhaul = _mapping(_mapping(values.get("interconnect")).get("endpointBackhaul"))
    hysteria = _mapping(endpoint_backhaul.get("hysteria2"))
    if not endpoint_backhaul.get("enabled") or not hysteria.get("enabled"):
        raise SystemExit("interconnect.endpointBackhaul.hysteria2.enabled=true is required")

    servers = _mapping(_mapping(values.get("topology")).get("servers"))
    endpoint_ip = _public_ipv4(
        _mapping(servers.get("endpoint")).get("publicIp"),
        field_name="topology.servers.endpoint.publicIp",
    )
    allowed = sorted(
        {
            _public_ipv4(value, field_name="interconnect.endpointBackhaul.hysteria2.allowedSources[]")
            for value in hysteria.get("allowedSources", [])
        }
    )
    if not allowed:
        raise SystemExit("interconnect.endpointBackhaul.hysteria2.allowedSources is required")

    try:
        port = int(hysteria.get("endpointPort") or 0)
    except (TypeError, ValueError) as exc:
        raise SystemExit("interconnect.endpointBackhaul.hysteria2.endpointPort must be a valid UDP port") from exc
    if port < 1 or port > 65535:
        raise SystemExit("interconnect.endpointBackhaul.hysteria2.endpointPort must be a valid UDP port")

    return "\n".join(
        [
            "# Generated by deploy/k3s/universal-entry-endpoint-backhaul-firewall.py. Do not edit.",
            "table inet tracegate_universal_entry_endpoint_backhaul {",
            "  chain input {",
            "    type filter hook input priority -11; policy accept;",
            f"    ip daddr {endpoint_ip} udp dport {port} ip saddr {{ {', '.join(allowed)} }} accept",
            f"    ip daddr {endpoint_ip} udp dport {port} reject with icmp type port-unreachable",
            "  }",
            "}",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the Universal Entry Endpoint Hysteria2 source policy.")
    parser.add_argument("--chart-values", required=True, type=Path)
    parser.add_argument("--values", required=True, type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = render(_merge(_read_yaml(args.chart_values), _read_yaml(args.values)))
    if args.output:
        args.output.write_text(output, encoding="utf-8")
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
