#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections.abc import Mapping
import ipaddress
from pathlib import Path
from typing import Any

import yaml


def _read_yaml(path: Path) -> dict[str, Any]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        raise SystemExit(f"values file must be a YAML mapping: {path}")
    return raw


def _merge(base: dict[str, Any], override: Mapping[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, Mapping) and isinstance(merged.get(key), dict):
            merged[key] = _merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def _mapping(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _public_ipv4(value: object, *, field_name: str) -> str:
    raw = str(value or "").strip()
    try:
        parsed = ipaddress.ip_address(raw)
    except ValueError as exc:
        raise SystemExit(f"{field_name} must be a public IPv4 address") from exc
    if parsed.version != 4 or not parsed.is_global:
        raise SystemExit(f"{field_name} must be a public IPv4 address")
    return str(parsed)


def _public_ipv4_network(value: object) -> str:
    raw = str(value or "").strip()
    try:
        network = ipaddress.ip_network(raw, strict=False)
    except ValueError as exc:
        raise SystemExit("architecture.universalEntry.originFirewall.allowedSourceCidrs must contain IPv4 CIDRs") from exc
    if network.version != 4 or not network.is_global:
        raise SystemExit("architecture.universalEntry.originFirewall.allowedSourceCidrs must contain public IPv4 CIDRs")
    return str(network)


def render(values: dict[str, Any]) -> str:
    architecture = _mapping(values.get("architecture"))
    universal = _mapping(architecture.get("universalEntry"))
    if not universal.get("enabled"):
        raise SystemExit("architecture.universalEntry.enabled=true is required")

    firewall = _mapping(universal.get("originFirewall"))
    if not firewall.get("required") or not firewall.get("denyDirectAccess"):
        raise SystemExit("Universal Entry origin firewall must be required and deny direct access")

    topology = _mapping(values.get("topology"))
    servers = _mapping(topology.get("servers"))
    entry_ip = _public_ipv4(_mapping(servers.get("entry")).get("publicIp"), field_name="topology.servers.entry.publicIp")

    gateway = _mapping(values.get("gateway"))
    entry_role = _mapping(_mapping(gateway.get("roles")).get("entry"))
    try:
        public_port = int(_mapping(entry_role.get("ports")).get("publicTcp") or 0)
    except (TypeError, ValueError) as exc:
        raise SystemExit("gateway.roles.entry.ports.publicTcp must be 443") from exc
    if public_port != 443:
        raise SystemExit("gateway.roles.entry.ports.publicTcp must be 443")

    allowed = sorted({_public_ipv4_network(value) for value in firewall.get("allowedSourceCidrs", [])})
    if not allowed:
        raise SystemExit("architecture.universalEntry.originFirewall.allowedSourceCidrs is required")

    return "\n".join(
        [
            "# Generated by deploy/k3s/universal-entry-origin-firewall.py. Do not edit.",
            "table inet tracegate_universal_entry_origin {",
            "  chain input {",
            "    type filter hook input priority -11; policy accept;",
            f"    ip daddr {entry_ip} tcp dport 443 ip saddr {{ {', '.join(allowed)} }} accept",
            f"    ip daddr {entry_ip} tcp dport 443 reject with tcp reset",
            "  }",
            "}",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the mandatory Cloudflare-only Universal Entry origin policy.")
    parser.add_argument("--chart-values", required=True, type=Path)
    parser.add_argument("--values", required=True, type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = render(_merge(_read_yaml(args.chart_values), _read_yaml(args.values)))
    if args.output:
        args.output.write_text(output, encoding="utf-8")
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
