# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xray/app/observatory/command/command.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'xray/app/observatory/command/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xray.app.observatory import config_pb2 as xray_dot_app_dot_observatory_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*xray/app/observatory/command/command.proto\x12\x1cxray.app.observatory.command\x1a!xray/app/observatory/config.proto\"\x1a\n\x18GetOutboundStatusRequest\"T\n\x19GetOutboundStatusResponse\x12\x37\n\x06status\x18\x01 \x01(\x0b\x32\'.xray.app.observatory.ObservationResult\"\x08\n\x06\x43onfig2\x9d\x01\n\x12ObservatoryService\x12\x86\x01\n\x11GetOutboundStatus\x12\x36.xray.app.observatory.command.GetOutboundStatusRequest\x1a\x37.xray.app.observatory.command.GetOutboundStatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xray.app.observatory.command.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETOUTBOUNDSTATUSREQUEST']._serialized_start=111
  _globals['_GETOUTBOUNDSTATUSREQUEST']._serialized_end=137
  _globals['_GETOUTBOUNDSTATUSRESPONSE']._serialized_start=139
  _globals['_GETOUTBOUNDSTATUSRESPONSE']._serialized_end=223
  _globals['_CONFIG']._serialized_start=225
  _globals['_CONFIG']._serialized_end=233
  _globals['_OBSERVATORYSERVICE']._serialized_start=236
  _globals['_OBSERVATORYSERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
