TRACEGATE_PUBLIC_TCP_PORT = 443
TRACEGATE_PUBLIC_UDP_PORT = 4443
TRACEGATE_NAIVEPROXY_HOST = "auth.example.com"
TRACEGATE_NAIVEPROXY_PUBLIC_TCP_PORT = 443
TRACEGATE_NAIVEPROXY_PUBLIC_UDP_PORT = 443
TRACEGATE_NAIVEPROXY_DEMUX_TCP_PORT = 11443
TRACEGATE_FORBIDDEN_PUBLIC_TCP_PORT = 8443
TRACEGATE_FORBIDDEN_PUBLIC_UDP_PORT = 8443
